services:
  app:
    build: .
    restart: unless-stopped
    environment:
      STREAMLIT_SERVER_ENABLECORS: "false"   # safe behind reverse proxy
      STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION: "true"
    healthcheck:
      test: ["CMD-SHELL","wget -qO- http://localhost:8501/_stcore/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
    expose:
      - "8501"

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      app:
        condition: service_healthy

volumes:
  caddy_data:
  caddy_config:
